web:
  image: abdelkader/spring
  ports:
    - "8081:8080"
    - "9990:9990"

  volumes:
    - /opt/DockerFiles/Compose/Wildfly/DeployedWars:/opt/jboss/wildfly/standalone/deployments/
  links:
    - db
  environment:
    - DEBUG=true
db:
  # this allowed the building of the custom configuration I created above
  # which resides in a 'MySql' subdirectory
  build: BD 
  # exposes the port to the shared appliance, but not to the outside world
  
